#pragma once
#include <GLFW/glfw3.h>
namespace OpenGL
{
#define MOUSE_LEFT						GLFW_MOUSE_BUTTON_1
#define MOUSE_RIGHT						GLFW_MOUSE_BUTTON_2
#define MOUSE_MIDDLE					GLFW_MOUSE_BUTTON_3

#define MOUSE_BUTTON_PRESS				GLFW_PRESS
#define MOUSE_BUTTON_RELEASE			GLFW_RELEASE

#define KEYBOARD_W						GLFW_KEY_W
#define KEYBOARD_S						GLFW_KEY_S
#define KEYBOARD_A						GLFW_KEY_A
#define KEYBOARD_D						GLFW_KEY_D

#define DEFAULT_RESOLUTION_X			1024
#define DEFAULT_RESOLUTION_Y			768
}